import React, { useEffect } from "react";
import SideMenu from "./SideMenu";
import Head from "next/head";
import { useRouter } from "next/router";
//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";     
    
//core
import "primereact/resources/primereact.min.css";          
type Proptype = {
  children: React.ReactNode;
};

export default function Layout({ children }: Proptype): JSX.Element {
  // const router = useRouter()
  // const {user} = useUser();
  // useEffect(()=>{
  //   if(!user){
  //     router.push('/login')
  //   }else {
  //     router.push('/dashboard')
  //   }
  // },[])
  return (
    <>
      <Head>
        <title>My Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SideMenu>
          <main className="bg-gray-100 min-h-screen">{children}</main>
        </SideMenu>
      </div>
    </>
  );
}
